djangoProject1/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register_product/', include('reg_product.urls')),
    path('products/', include('product.urls')),
    path('inputtabel/', include('inputtabel.urls')),
    path('', include('home.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from . import views

app_name = "home"

urlpatterns = [
    path('', views.reg_product, name="home"),
]

inputtabel/urls.py
from django.urls import path
from . import views

app_name = "input"

urlpatterns = [
    path('', views.input, name="inputtabel"),
    # path("", views.Prouduct_list, name="innnnn")
]

product/urls.py
from django.urls import path
from . import views

app_name = "product"

urlpatterns = [
    path('', views.Prouduct_list, name="products"),
    path("<int:id>/", views.Product_detail, name="product"),
    path("category/<slug:category>", views.prouduct, name="product_category"),
]

reg_product/urls.py
from django.urls import path
from . import views

app_name = "register_product"

urlpatterns = [
    path('', views.reg_product, name="register_product")
]

templates/partials/_footer.html
{% load static %}
<style>
    footer {
        background: url("{% static 'assets/img/green-texture_1160-912.jpg' %}") center / cover;
    }
</style>
<footer style="margin-top: 183px;">
    <div class="container py-4 py-lg-5">
        <div class="row justify-content-center">
            <div class="col-sm-4 col-md-3 text-center text-lg-start d-flex flex-column item">
                <h3 class="fs-6">خدمات</h3>
                <ul class="list-unstyled">
                    <li><a class="link-secondary" href="{% url 'register_product:register_product' %}"
                           style="color: rgb(57,57,57);">آموزش</a></li>
                    <li><a class="link-secondary" href="{% url 'input:inputtabel' %}" style="color: rgb(57,57,57);">ایده
                        پردازی</a></li>
                    <li><a class="link-secondary" href="{% url 'input:inputtabel' %}" style="color: rgb(57,57,57);">کارآفرینی</a>
                    </li>
                </ul>
            </div>
            <div class="col-sm-4 col-md-3 text-center text-lg-start d-flex flex-column item">
                <h3 class="fs-6">اطلاعات</h3>
                <ul class="list-unstyled">
                    <li><a class="link-secondary" href="{% url 'input:inputtabel' %}" style="color: rgb(57,57,57);">اقتصاد
                        برتر چیست ؟</a></li>
                    <li><a class="link-secondary" href="{% url 'input:inputtabel' %}" style="color: rgb(57,57,57);">کارآفرینی
                        چگونه است ؟</a></li>
                </ul>
            </div>
            <div class="col-lg-3 text-center text-lg-start d-flex flex-column align-items-center order-first align-items-lg-start order-lg-last item social">
                <div class="fw-bold d-flex align-items-center mb-2"><span
                        class="bs-icon-sm bs-icon-rounded bs-icon-primary d-flex justify-content-center align-items-center bs-icon me-2"
                        style="background: url(&quot;{% static "assets/img/Asset-5-min.png" %}&quot;) center / cover no-repeat;width: 84px;height: 83px;"></span><span>Brand</span>
                </div>
                <p class="text-muted copyright"><strong>هدف ما تولید و اشتغال زایی با تکیه بر علم اقتصاد برتر و رواج
                    اخلاق مداری و صداقت در جامعه و پیشرفت همگانی</strong><br></p>
            </div>
        </div>
        <hr>
        <div class="d-flex justify-content-between align-items-center pt-3">
            <p class="text-muted mb-0">Copyright © 2022 Brand</p>
            <ul class="list-inline mb-0">
                <li class="list-inline-item">
                    <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="currentColor"
                         viewBox="0 0 16 16" class="bi bi-facebook">
                        <path d="M16 8.049c0-4.446-3.582-8.05-8-8.05C3.58 0-.002 3.603-.002 8.05c0 4.017 2.926 7.347 6.75 7.951v-5.625h-2.03V8.05H6.75V6.275c0-2.017 1.195-3.131 3.022-3.131.876 0 1.791.157 1.791.157v1.98h-1.009c-.993 0-1.303.621-1.303 1.258v1.51h2.218l-.354 2.326H9.25V16c3.824-.604 6.75-3.934 6.75-7.951z"></path>
                    </svg>
                </li>
                <li class="list-inline-item"></li>
                <li class="list-inline-item">
                    <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="currentColor"
                         viewBox="0 0 16 16" class="bi bi-instagram">
                        <path d="M8 0C5.829 0 5.556.01 4.703.048 3.85.088 3.269.222 2.76.42a3.917 3.917 0 0 0-1.417.923A3.927 3.927 0 0 0 .42 2.76C.222 3.268.087 3.85.048 4.7.01 5.555 0 5.827 0 8.001c0 2.172.01 2.444.048 3.297.04.852.174 1.433.372 1.942.205.526.478.972.923 1.417.444.445.89.719 1.416.923.51.198 1.09.333 1.942.372C5.555 15.99 5.827 16 8 16s2.444-.01 3.298-.048c.851-.04 1.434-.174 1.943-.372a3.916 3.916 0 0 0 1.416-.923c.445-.445.718-.891.923-1.417.197-.509.332-1.09.372-1.942C15.99 10.445 16 10.173 16 8s-.01-2.445-.048-3.299c-.04-.851-.175-1.433-.372-1.941a3.926 3.926 0 0 0-.923-1.417A3.911 3.911 0 0 0 13.24.42c-.51-.198-1.092-.333-1.943-.372C10.443.01 10.172 0 7.998 0h.003zm-.717 1.442h.718c2.136 0 2.389.007 3.232.046.78.035 1.204.166 1.486.275.373.145.64.319.92.599.28.28.453.546.598.92.11.281.24.705.275 1.485.039.843.047 1.096.047 3.231s-.008 2.389-.047 3.232c-.035.78-.166 1.203-.275 1.485a2.47 2.47 0 0 1-.599.919c-.28.28-.546.453-.92.598-.28.11-.704.24-1.485.276-.843.038-1.096.047-3.232.047s-2.39-.009-3.233-.047c-.78-.036-1.203-.166-1.485-.276a2.478 2.478 0 0 1-.92-.598 2.48 2.48 0 0 1-.6-.92c-.109-.281-.24-.705-.275-1.485-.038-.843-.046-1.096-.046-3.233 0-2.136.008-2.388.046-3.231.036-.78.166-1.204.276-1.486.145-.373.319-.64.599-.92.28-.28.546-.453.92-.598.282-.11.705-.24 1.485-.276.738-.034 1.024-.044 2.515-.045v.002zm4.988 1.328a.96.96 0 1 0 0 1.92.96.96 0 0 0 0-1.92zm-4.27 1.122a4.109 4.109 0 1 0 0 8.217 4.109 4.109 0 0 0 0-8.217zm0 1.441a2.667 2.667 0 1 1 0 5.334 2.667 2.667 0 0 1 0-5.334z"></path>
                    </svg>
                </li>
            </ul>
        </div>
    </div>
</footer>

templates/partials/_header.html
{% load static %}
<nav class="navbar navbar-light navbar-expand-md fixed-top d-grid navbar-shrink py-3" id="mainNav"
     style="border-bottom-right-radius: 31px;border-bottom-left-radius: 31px;padding: 2px 0px;">
    <div class="container"><a class="navbar-brand d-flex align-items-center" href="{% url 'home:home' %}"><span
            class="bs-icon-sm bs-icon-rounded bs-icon-primary d-flex justify-content-center align-items-center bs-icon me-2"
            style="background: url(&quot;{% static 'assets/img/Asset-5-min.png' %}&quot;) center / cover no-repeat;width: 40px;height: 40px;"></span><span
            style="color: rgb(58,58,58);margin-left: 25px;">Brand</span></a>
        <div class="collapse navbar-collapse" id="navcol-1">
            <ul class="navbar-nav mx-auto" style="color: rgb(255,255,255);font-size: 20px;">
                <li class="nav-item"><a class="nav-link" href="{% url 'home:home' %}"
                                        style="color: rgb(58,58,58);">خانه</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'input:inputtabel' %}"
                                        style="color: rgb(58,58,58);">اتاق معماری ایده ها</a></li>
                <li class="nav-item"><a class="nav-link" href="#" style="color: rgb(58,58,58);">میز آورده ها</a></li>
                <li class="nav-item"><a class="nav-link active" href="{% url 'product:products' %}"
                                        style="color: rgb(58,58,58);">نمایشگاه خرما</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'register_product:register_product' %}"
                                        style="color: rgb(58,58,58);">ثبت محصول</a></li>
            </ul>
        </div>
        <button data-bs-target="#navcol-1" data-bs-toggle="collapse" class="navbar-toggler order-first"><span
                class="visually-hidden">Toggle navigation</span><span class="navbar-toggler-icon"></span></button>
    </div>
</nav>
{#{% if request.resolver_match.url_name == "{% url 'register_product:register_product' %}" %}class="active" {% else %} class="nav-link" {% endif %}#}